name: kcli-test
on: [push]
jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        run: |
          sudo apt update
          sudo apt install qemu libvirt-daemon-system genisoimage
          id
          sudo adduser $USER libvirt
          id
          newgrp libvirt
          id
          sudo chmod a+rw /var/run/libvirt/libvirt-sock
      - uses: actions/checkout@v2
      - name: Install kcli
        run: |
          curl https://raw.githubusercontent.com/karmab/kcli/main/install.sh | bash
      #- name: Setup upterm session
      #  uses: lhotari/action-upterm@v1
      - name: Run kcli tests
        timeout-minutes: 30
        run: |
          id
          ssh-keygen -b 2048 -t rsa -f ~/.ssh/testkey -N ""
          sudo kcli create pool -p /var/lib/libvirt/images default
          sudo kcli download image fedora37
          newgrp libvirt <<EONG
          id
          cd test/kcli
          make _output/configure-ovs.sh
          kcli create plan -f plans/single-nic.yml -Poutput_dir=`pwd`/_output/test
          make runtest
          EONG
      - name: Archive output folder
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs
          path: test/kcli/_output

