name: kcli-test
on: [push]
jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        run: |
          sudo apt update
          sudo apt install qemu libvirt-daemon-system genisoimage
      - uses: actions/checkout@v2
      - name: Install kcli
        run: |
          curl https://raw.githubusercontent.com/karmab/kcli/main/install.sh | bash
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Run kcli tests
        timeout-minutes: 15
        run: |
          cd test/kcli
          sudo kcli create pool -p /var/lib/libvirt/images default
          sudo kcli download image fedora37
          sudo make runtest
      - name: Archive output folder
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs
          path: test/kcli/_output

