name: kcli-test
on: [push]
jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        #uses: docker/setup-qemu-action@v2
        #with:
        #  platforms: "x86-64"
        run: |
          sudo apt update
          sudo apt install qemu libvirt-daemon-system
      - uses: actions/checkout@v2
      - name: Install kcli
        run: |
          curl https://raw.githubusercontent.com/karmab/kcli/main/install.sh | bash
      - name: Run kcli tests
        run: |
          cd test/kcli
          sudo kcli download image fedora37
          sudo make runtest
